// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZudg6bbRJowY8YEluTerFxEPHLNhYmqc',
    appId: '1:325858491682:android:4e1bc5c23d5192d7d6397b',
    messagingSenderId: '325858491682',
    projectId: 'chetapp-1ecfc',
    databaseURL: 'https://chetapp-1ecfc-default-rtdb.firebaseio.com',
    storageBucket: 'chetapp-1ecfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8OIf7e8ADFbN7WbhSF0bRvg19b0nNHUA',
    appId: '1:325858491682:ios:140344b63c1e1a29d6397b',
    messagingSenderId: '325858491682',
    projectId: 'chetapp-1ecfc',
    databaseURL: 'https://chetapp-1ecfc-default-rtdb.firebaseio.com',
    storageBucket: 'chetapp-1ecfc.appspot.com',
    androidClientId: '325858491682-5qf0ejses2ulvaspps78lqv9tun9brj8.apps.googleusercontent.com',
    iosClientId: '325858491682-gv9klif7kusfins5lc25qiv48u2jhl9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chetApp',
  );

}